version: 2
jobs:
   build:
     working_directory: ~/mosquitto
     machine: true
     #docker:
     #  - image: gerey/mosquitto:latest
     steps:
       - checkout
       - run: sudo apt-get update -qq
       - run: sudo apt-get install -y debhelper libc-ares-dev libssl-dev libwrap0-dev python-all python3-all uthash-dev uuid-dev libuuid1 xsltproc docbook-xsl
       - run: sudo make
       - run: sudo make test